language: python

sudo: false
dist: xenial

cache:
  pip: true
  directories:
    - $HOME/.cache/pypoetry

install:
  - curl -sSL https://raw.githubusercontent.com/sdispater/poetry/master/get-poetry.py | python
  - source $HOME/.poetry/env
  - poetry install

script:
  - poetry run pytest
  - poetry run black --check pslib tests

jobs:
  include:
    - python: 3.8

    - stage: publish
      python: 3.8
      if: tag IS present
      script:
        - poetry build
        - poetry publish --username="$PYPI_USERNAME" --password="$PYPI_PASSWORD"
